# Generated by Django 5.1.7 on 2025-03-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_task_assigned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_by',
        ),
    ]
